name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker images
      run: sudo docker build . -t frontend 
    - name: remomve existing container
      run:  sudo docker ps --quiet --filter="name=frontend" | xargs --no-run-if-empty docker rm -f
    - name: run the Docker container
      run: sudo docker run -dt -p 80:80 --restart always --name frontend frontend

